name: CI workflow

on:
  push:
    branches: # Array of strings
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim
    steps: # Array of objects or list of dictionaries [{"name": "Checkout", "uses": "actions/checkout@v3"}]
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        # '|' (vertical bar) indicates that the following block of lines is a string value that will have the line breaks preserved.
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 service --count --max-complexity=10 --max-line-length=127 --statistics

      - name: Run unit tests with nose
        run: nosetests -v --with-spec --spec-color --with-coverage --cover-package=app
